$("#m-home-page").click(function(){
	window.location.href="../index.php";
});
$("#m-exit").click(function(){
	window.location.href="./index.html";
});
$("#manager-add-news").click(function(){
	window.location.href="./anew.php";
});
$("#manager-view-user").click(function(){
	window.location.href="./auser.php";
});
$("#manager-view-news").click(function(){
	window.location.href="./anews.php";
});
$("#manager-view-privilege").click(function(){
	window.location.href="./aprivileges.php";
});
$("#manager-view-shopper").click(function(){
	window.location.href="./ashoppers.php";
});
$("#manager-view-goods").click(function(){
	window.location.href="./agoods.php";
});
$("#manager-view-order").click(function(){
	window.location.href="./aorders.php";
});
$("#manager-cache").click(function(){
	window.location.href="./acache.php"
});
$("#fenqi-order").click(function(){
	window.location.href="./aorders.php";
});
$("#jifen-order").click(function(){
	window.location.href="./ajorders.php";
});
$("#basic-config").click(function(){
	window.location.href="./abasic.php";
});
